### ISSUE TITLE
Change Qua.GetScrollVelocityAt() to return null instead of the first SV for times before the first SV

### ISSUE THREAD

**Issue by Illuminati-CRAZ** [Quaver/Quaver.API#98]
Currently for times before the first SV of a map, the method returns the first SV of the map. However during gameplay, notes coming before the first SV don't use the first SV's multiplier, but rather 1 (or a different number, if InitialScrollVelocity is set to a different number in the file). I think it would make more sense if it returned null instead, as there isn't an SV associated with notes and timing lines before the first SV.

From what I can tell, changing it to return null instead of the first SV would minimally affect just the editor (and in my opinion make things make more sense):
 - For times before the first SV, Ctrl + I would place an SV of multiplier 1 instead of one with a multiplier the same as the first
 - Opening the SV panel at a time before the first SV would cause no SV to be selected
 - Adding an SV before the first one would place it with a multiplier of 1 instead of a multiplier the same as the first
 - Pressing the Select Current SV button would select nothing for times before the first SV

**Comment by YaLTeR** [comment]
> notes coming before the first SV don't use the first SV's multiplier, but rather 1 (or a different number, if InitialScrollVelocity is set to a different number in the file)

In "BPM affects SV" mode (also how osu works) the first SV actually determines the SV anywhere before it too IIRC.

**Comment by Illuminati-CRAZ** [comment]
I checked and the first SV doesn't determine the SV before it with BPM affects SV turned on.

**Comment by IceDynamix** [comment]
https://github.com/Quaver/Quaver.API/blob/master/Quaver.API/Maps/Qua.cs#L122

**Comment by Illuminati-CRAZ** [comment]
I guess I'll make a PR then
